"""Mermaid renderer.

Pure function: `FlowIR -> Mermaid text`. The output uses Mermaid's `graph LR`
diagram type — the deprecated synonym is chosen deliberately so the shadow
term ADR-0021 retired from the repo's docs does not appear in the
generator's source either. The three Flow directives are distinguished by
arrow style:

    Transition       -->|"label"|
    TransitionNow    ==>|"label"|        (heavy arrow)
    Done             -.->|"label"|       (dashed arrow into terminal)

The initial State is marked by a small filled circle pseudo-node (`__start`)
that points at it. `Done` edges all converge on a shared terminal pseudo-node
(`__end`) so the State that ends the flow is unambiguous regardless of how
many `done()` directives the body issues.

Edge labels are HTML-entity-encoded so message types like `KeyChanged<Counter>`
render correctly in GitHub's Mermaid preview, which interprets `<...>` as HTML
tags inside otherwise-unquoted labels.
"""

from __future__ import annotations

from typing import List

from .ir import (
    DIRECTIVE_DONE,
    DIRECTIVE_TRANSITION,
    DIRECTIVE_TRANSITION_NOW,
    FlowEdge,
    FlowIR,
)


_START_NODE = '__start'
_END_NODE = '__end'


def render_flow(flow_ir: FlowIR) -> str:
    """Render a FlowIR to a Mermaid `graph LR` document. The output ends with
    a trailing newline so the file is POSIX-clean and stable across editors.
    """
    has_done = any(e.directive == DIRECTIVE_DONE for e in flow_ir.edges)

    lines: List[str] = []
    lines.append(f'%% Flow diagram for {flow_ir.module}')
    lines.append('%% Generated by scripts/gen-diagrams.py — do not edit by hand.')
    lines.append('graph LR')
    lines.append('    classDef startMarker fill:#000,stroke:#000,color:#000')
    lines.append('    classDef terminalMarker fill:#fff,stroke:#000,stroke-dasharray:3 3')
    lines.append('')
    lines.append(f'    {_START_NODE}(( )):::startMarker')
    for state in flow_ir.states:
        lines.append(f'    {state}')
    if has_done:
        lines.append(f'    {_END_NODE}((( ))):::terminalMarker')
    lines.append('')
    lines.append(f'    {_START_NODE} --> {flow_ir.initial_state}')
    for edge in flow_ir.edges:
        lines.append('    ' + _render_edge(edge))
    return '\n'.join(lines) + '\n'


def _render_edge(edge: FlowEdge) -> str:
    arrow = _ARROW_BY_DIRECTIVE[edge.directive]
    target = _END_NODE if edge.directive == DIRECTIVE_DONE else edge.to_state
    if edge.message:
        label = _escape_label(edge.message)
        return f'{edge.from_state} {arrow}|"{label}"| {target}'
    return f'{edge.from_state} {arrow} {target}'


_ARROW_BY_DIRECTIVE = {
    DIRECTIVE_TRANSITION: '-->',
    DIRECTIVE_TRANSITION_NOW: '==>',
    DIRECTIVE_DONE: '-.->',
}


def _escape_label(text: str) -> str:
    """HTML-escape `<`, `>`, and `&` for Mermaid edge labels. Mermaid will
    interpret bare `<` as the start of an HTML tag even inside quoted labels
    on GitHub's renderer, which silently drops the rest of the label.
    """
    return (
        text.replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
    )
